alias rm-identifier='rm *.Identifier'
alias sros='source /opt/ros/melodic/setup.bash'
alias va='vim ~/.oh-my-zsh/custom/aliases.zsh'
alias szrc='source ~/.zshrc'
alias vzrc='vim ~/.zshrc'
alias vvrc='vim ~/.vimrc'
alias py3='python3'
alias gzkill='pkill gzclient && pkill gzserver'
alias tma='tmux a -t'
alias tmk='tmux kill-session -t'
alias tmn='tmux new -s'
alias rpp='export ROS_PACKAGE_PATH=`pwd`:$ROS_PACKAGE_PATH'
alias dsb='source devel/setup.bash'

alias g++='g++ -pedantic-errors -Wall -Weffc++ -Wextra -Wconversion -Wsign-conversion -Werror -std=c++20'
