alias rm-identifier='rm *.Identifier'
alias sros='source /opt/ros/melodic/setup.bash'
alias vba='vim ~/.bash_aliases'
alias sbrc='source ~/.bashrc'
alias vbrc='vim ~/.bashrc'
alias vvrc='vim ~/.vimrc'
alias sw='cd ~/hcrl/steven_ws/'
alias tw='cd ~/hcrl/tutorial_ws/'
alias py3='python3'
alias gzkill='pkill gzclient && pkill gzserver'
alias tma='tmux a -t'
alias tmk='tmux kill-session -t'
alias tmn='tmux new -s'
alias rpp='export ROS_PACKAGE_PATH=`pwd`:$ROS_PACKAGE_PATH'
alias dsb='source devel/setup.bash'
alias essh='eval $(ssh-agent)'
